### ISSUE TITLE
Don't understand this:

### ISSUE THREAD

**Issue by bkuner** [ralphlange/opcua#10]
in DataElementuaSdk.cpp, readInt32(), line 132

```
 line 132    if (OpcUa_IsNotGood(tempValue.toInt32(v)))
        throw std::runtime_error(SB() << "incoming data out-of-bounds");

```
To me there is the value of data compared to 0xC0000000. Seems to be nonsens.
See definition of macro OpcUa_IsNotGood():
```
/* tests if a status code is not good. */
#define OpcUa_IsNotGood(xCode) (((xCode) & 0xC0000000) != 0x00000000)

```

**Comment by ralphlange** [comment]
`tempValue` is a `UaVariant` (defined a few lines up).

The method to convert a UaVariant to an Int32 is defined (in `uavariant.h`) as
```
    OpcUa_StatusCode toInt32(OpcUa_Int32& val) const;
```
which makes the result testable using the `OpcUa_IsNotGood()` macro.
