### ISSUE TITLE
path for opcuaSaveRejected at Windows

### ISSUE THREAD

**Issue by nugatritter** [ralphlange/opcua#103]
**`opcuaSaveRejected ` always writes to /tmp/**
rejected (untrusted) server certificates are always written to `/tmp/<ioc>@<host>`
Under Windows, this directory does not exist and is not created.

**To Reproduce**
1.  Setup opcuaIoc under Windows with parameter `opcuaSaveRejected `
2.  Start opcuaIoc and the error is displayed

**Expected behavior**
opcuaIoc should create / use directory `%AppData%\<ioc>@<host>` when using `opcuaSaveRejected`

**Comment by ralphlange** [comment]
Well spotted!
I did change the way that a directory is created so that it works under Windows, but I did not change the default location.

(Note that `opcuaSaveRejected` has a parameter where you can set the directory to write to.)
