### ISSUE TITLE
should not install rules

### ISSUE THREAD

**Issue by bfrk** [ralphlange/opcua#104]
Using the latest released version v.0.5.2.

`devOpcuaSup/UaSdk/Makefile` installs build rules:

```
CFG += RULES_OPCUA
CFG += CONFIG_OPCUA
```

This is bad and should not be needed. It is bad, because e.g. the following line in RULES_OPCUA
```
USR_SYS_LIBS += $(UASDK_LIBS)
```
means that _every_ program or library built inside a module or application that has opcua support in its configure/RELEASE will now be linked against the UASDK_LIBS.

It is unneeded because I have removed the make rule installation and can build our applications just fine w/o them.

**Comment by ralphlange** [comment]
The latest released version is v0.8.0.

I get your point. It is true that some types of builds (including yours) might not need the rules. Others do.

**Comment by bfrk** [comment]
> The latest released version is v0.8.0.

Sorry.

> I get your point. It is true that some types of builds (including yours) might not need the rules. Others do.

I wouldn't mind the extra rules if they didn't break our builds. The problem is that these libraries don't exist for all target archs (e.g. RTEMS and other cross archs). Generally, I don't think it is correct to set things like USR_LIBS in rules published by a support module as that forces all downstream static libraries and binaries to link them. I think it would be better to just define a variable that contains all the needed libraries and let users do their own xxx_LIBS +=, just as they have to do for any other libraries (base or support modules).

**Comment by bfrk** [comment]
BTW, the actual rules (not variable definitions) in RULES_OPCUA look like they are for use within opcua itself, not for users to include.

**Comment by ralphlange** [comment]
Depends on the build type (SYSTEM | PROVIDED | EMBED).

**Comment by ralphlange** [comment]
But your point about not setting the global variables is valid.

**Comment by ralphlange** [comment]
As discussed:
I left the four deploy types around, as they all seem to have valid use cases. The remaining parts of the PR (#106) are merged with a few changes.
Thanks for pointing this out!
