### ISSUE TITLE
Allow the same options for monitor and autoconnect

### ISSUE THREAD

**Issue by jeonghanlee** [ralphlange/opcua#16]
@ralphlange 

**Is your feature request related to a problem? Please describe.**

It is not any problem, but it would be better to use **the same options**. For example,  

In https://github.com/ralphlange/opcua/blob/master/devOpcuaSup/linkParser.cpp#L101, 
the available options are _YyTt1_ or _NnFf0_ in order to enable or disable `monitor` such as
```
                char c = optval[0];
                if (strchr("YyTt1", c))
                    pinfo->monitor = true;
                else if (strchr("NnFf0", c))
                    pinfo->monitor = false;
                else
```
However,  in https://github.com/ralphlange/opcua/blob/master/devOpcuaSup/iocshIntegration.cpp#L104 
 the available options for `autoconnect` have _YyTt_ or _NnFf_ such as 
```
            char c = args[3].sval[0];
            if (c == 'n' || c == 'N' || c == 'f' || c == 'F') {
                autoconnect = false;
            } else if (c != 'y' && c != 'Y' && c != 't' && c != 'T') {
                errlogPrintf("invalid argument #4 (autoconnect) '%s'\n",
                             args[6].sval);
            }
```
**Describe the solution you'd like**

It would be better to use _YyTt1_ or _NnFf0_ in both places.  

Thanks,
@jeonghanlee

**Comment by ralphlange** [comment]
Yep. Well spotted!
I will take care of this when I'm back at work next week.
