### ISSUE TITLE
opcuaSetOption 

### ISSUE THREAD

**Issue by jeonghanlee** [ralphlange/opcua#59]
**Describe the bug**
Without arguments, if one executes opcuaSetOption, there is a segmentation fault. 

**To Reproduce**
1.  Build the example ioc
2.  Run the ioc 
3.  within ioc prompt, 
```
epics> opcuaSetOption
missing argument #1 (session name)
missing argument #2 (option name)
Segmentation fault
```
4.  

**Expected behavior**

It will print out "help"

**Setup (please complete the following information if applicable):**
-   OPCUA Support: a52002c
-   Platform: Debian 10 / CentOS 7
-   EPICS Base: 7.0.3 
-   Client library: UA SDK 1.7.0
-   Server: Without any server 

**Additional context**

**Comment by ralphlange** [comment]
Indeed, this crashes reproducibly.
Ouch. Thanks for pointing this out!
