### ISSUE TITLE
timestamp conversion

### ISSUE THREAD

**Issue by dirk-zimoch** [ralphlange/opcua#84]
https://github.com/ralphlange/opcua/blob/50211adb481a2c3b65a53a2949d7f50ae11c5d08/devOpcuaSup/UaSdk/ItemUaSdk.cpp#L147

I think this calculation drops part of the time stamp. It takes only milliseconds and 10_picoseconds into account but drops the microseconds and 100_nanoseconds parts. See UA SDK uabase/uabasecpp/uadatetime.cpp line 259ff.

Better cast to OpcUa_Int64 (see uadatetime.cpp line 122) yielding a counter of 100 ns steps, then % UA_SECS_TO_100NS  (1e7) to remove the whole seconds  (and get a 32 bit value) then multiply by 100 to get ns and then add the (10 picoseconds)/100.
(That the OpcUa_Int64 value has an offset to UNIX time does not matter because the modulo removes the whole seconds anyway.)

`static_cast<epicsUInt32>(static_cast<OpcUa_Int64>(dt) % UA_SECS_TO_100NS) * 100 + pico10 / 100;`

**Comment by ralphlange** [comment]
Well spotted!
I will use your suggestion, which seems to be correct.

Background: I was coding this by looking at the documentation of the `UaDateTime` class, which wasn't detailed enough for me to see I was missing parts.
No practical implications so far, as the S7-1500s deliver timestamps with 10ms resolution.
