### ISSUE TITLE
memory access exception in DataElementUaSdk::addElementToTree

### ISSUE THREAD

**Issue by nugatritter** [ralphlange/opcua#86]
**Describe the bug**
DataElementUaSdk::addElementToTree causes a memory access exception when parameter "fullpath" is empty

**To Reproduce**
1.  for error simulation set fullpath to empty in DataElement::addElementToTree function
2.  rebuild opcua
3.  rebuild "exampleTop" => opcuaIoc
4.  See error

**Expected behavior**
When "fullpath" in DataElementUaSdk::addElementToTree is empty then "path" will be empty too.
In this case the function path.find_last_of(separator) returns a random number and following path[sep-1] == '\\' causes a memory access exception

**Comment by ralphlange** [comment]
Yep. Good catch.
That while loop must test for sep == 0 and sep == std::string::npos (not found).
