### ISSUE TITLE
exampleTop/opcuaIocApp won't compile here

### ISSUE THREAD

**Issue by bkuner** [ralphlange/opcua#9]
without adding libcrypto to opcuaIoc libs:
Makefile:
```
# Add all the support libraries needed by this IOC
opcuaIoc_LIBS += opcua
opcuaIoc_SYS_LIBS += crypto

```

**Comment by ralphlange** [comment]
Example in place or copied out?
Which version of EPICS Base?
What's your setting of UASDK_DEPLOY_MODE?

Please try to supply enough information that I can try to reproduce the behavior.

**Comment by ralphlange** [comment]
What is your setting for UASDK_USE_CRYPTO in CONFIG_SITE(.local)?

**Comment by ralphlange** [comment]
My linker line looks exactly the same, but I am using SDK 1.5.5, and the binary does not need to be linked against libcrypto.

How did you build the SDK? Did you use the standard script (that actually does not build all libraries as shared libraries even if you tell it to)? I am patching the Unified Automation build script to do clean shared library and static library builds.
I think if you use the original build script, the one static library contains calls to libcrypto symbols creating a dependency even if you don't use the crypto things in the SDK.

**Comment by ralphlange** [comment]
Nevertheless: if `UASDK_USE_CRYPTO = YES`, libcrypto should appear on the linker line, so I will consider this a bug.

**Comment by bkuner** [comment]
don't use any local files here
```
# How the Unified Automation SDK shared libraries are deployed
#   SYSTEM = shared libs are in a system location
#   PROVIDED = shared libs are in $(UASDK_DIR)
#   INSTALL = shared libs are installed (copied) into this module
UASDK_DEPLOY_MODE = PROVIDED
UASDK_DIR = $(UASDK)/lib
# How the Unified Automation SDK libraries were built
UASDK_USE_CRYPTO = YES
UASDK_USE_XMLPARSER = YES

USR_CXXFLAGS_Linux += -std=c++11
USR_CXXFLAGS += -DUSE_TYPED_RSET


```
