### ISSUE TITLE
problem starting example IOC iocopcuaEx

### ISSUE THREAD

**Issue by dirk-zimoch** [ralphlange/opcua#90]
When starting the IOC (using EPICS 7.0 on Linux), it hangs forever (?) on the st.cmd line
`dbLoadDatabase("../../dbd/opcuaIoc.dbd",0,0)`

The arguments 0,0 seem to be for VxWorks only, not for Linux. No idea why it actually hangs (have not investigated)
Changing the line to this fixes it:
`dbLoadDatabase("../../dbd/opcuaIoc.dbd")`

**Comment by ralphlange** [comment]
These additional arguments are in the `st.cmd@Cross` version of the startup command file in [3.15](https://github.com/epics-base/epics-base/tree/3.15/src/template/base/top/iocBoot/ioc) and [7.0](https://github.com/epics-base/epics-base/blob/7.0/modules/database/src/template/top/iocBoot/ioc/st.cmd%40Cross).

They are in none of the other (Common, RTEMS, vxWorks) versions.

Works fine on my Linux systems. (Debian 9, Debian Testing, RHEL 7)
Will fix anyway.

**Comment by ralphlange** [comment]
```C
/* dbLoadDatabase */
static const iocshArg dbLoadDatabaseArg0 = { "file name",iocshArgString};
static const iocshArg dbLoadDatabaseArg1 = { "path",iocshArgString};
static const iocshArg dbLoadDatabaseArg2 = { "substitutions",iocshArgString};
static const iocshArg * const dbLoadDatabaseArgs[3] =
{
    &dbLoadDatabaseArg0,&dbLoadDatabaseArg1,&dbLoadDatabaseArg2
};
static const iocshFuncDef dbLoadDatabaseFuncDef =
    {"dbLoadDatabase",3,dbLoadDatabaseArgs};
static void dbLoadDatabaseCallFunc(const iocshArgBuf *args)
{
    iocshSetError(dbLoadDatabase(args[0].sval,args[1].sval,args[2].sval));
}
```
