### ISSUE TITLE
opcuaItem record has no accessible .VAL field

### ISSUE THREAD

**Issue by dirk-zimoch** [ralphlange/opcua#96]
The opcuaItem record is unique in having no .VAL field. That leads to the situation where `caget RECORD` fails even though the record exists. Following the principle of least surprise, accessing a record by record name only (without field) should not fail for existing and accessible records. What .VAL should map to is another question.

**Comment by ralphlange** [comment]
Ack. That's correct.
What would you like VAL to map to?

**Comment by dirk-zimoch** [comment]
Don't know. I am not familiar with that record type. I noticed it when trying to find out what that record type is about and what it contains (e.g. if I can see the received structure data or something like that).

**Comment by jalalmostafa** [comment]
What about a json string? Or a similar structure? When the user can benefit when he wants to archive the solution as it is.

**Comment by ralphlange** [comment]
I am not convinced.
My first S7 real world case has structures with up to 10k elements. The IOC would spend most of its time creating JSON objects that no one would ever read.

I will add the field with no mapping as a preliminary fix.

**Comment by ralphlange** [comment]
Well, turns out the opcuaItem record does have a `VAL` field, but it's set to `DBF_NOACCESS`. 
Which is not good if you don't have `special()` (`DBADDR`) treatment in place.
